name: iac-demo1-bicep
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy to
        required: true
        default: 'test'

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Action
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
          az group create --name "iac-demo1-bicep-${{ github.event.inputs.environment }}-rg" --location westeurope
              
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: "ac-demo1-bicep-${{ github.event.inputs.environment }}-rg"
        template: ./iac-demo1-bicep/main.bicep
        parameters: ./iac-demo1-bicep/parameters.test.bicepparam
        failOnStdErr: false
